# Generated by Django 5.2 on 2025-04-16 07:51

import batch_inspection.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PRF', '0011_remove_employee_email_and_more'),
        ('received_shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('inspection_id', models.CharField(default=batch_inspection.models.Inspection.generate_inspection_id, max_length=100, primary_key=True, serialize=False)),
                ('inspection_date', models.DateField()),
                ('inspection_result', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='inspections_id', to='PRF.employee')),
                ('shipment_id', models.ForeignKey(db_column='shipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='inspections_id', to='received_shipments.shipment')),
            ],
            options={
                'db_table': 'batch_inspection',
            },
        ),
    ]
