# Generated by Django 5.1.6 on 2025-03-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quotation_id', models.CharField(blank=True, max_length=50, null=True)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('document_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
            ],
            options={
                'db_table': 'purchase_order',
            },
        ),
    ]
