# Generated by Django 5.1.6 on 2025-04-02 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
        ('purchase_quotation', '0004_alter_quotationcontents_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_quotation.purchasequotation'),
        ),
    ]
