# Generated by Django 5.1.6 on 2025-04-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_alter_purchaseorder_quotation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
