# Generated by Django 5.1.6 on 2025-04-12 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_alter_purchaseorder_purchase_id'),
        ('purchase_quotation', '0008_delete_quotationcontents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation_id',
            field=models.ForeignKey(blank=True, db_column='quotation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_quotation.purchasequotation'),
        ),
    ]
