# Generated by Django 5.1.6 on 2025-03-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('purchase_order', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled'), ('Draft', 'Draft')], max_length=20)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
            ],
            options={
                'db_table': 'purchase_invoice',
            },
        ),
    ]
