# Generated by Django 5.1.6 on 2025-03-31 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apinvoice',
            table='purchasing.purchase_invoice',
        ),
    ]
