# Generated by Django 5.1.6 on 2025-03-31 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_apinvoice_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apinvoice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='apinvoice',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='apinvoice',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='apinvoice',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='applied_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='document_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='document_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='dpm_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='dpm_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='invoice_id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='purchase_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='apinvoice',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='apinvoice',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled'), ('Draft', 'Draft')], default='Draft', max_length=20),
        ),
        migrations.AlterModelTable(
            name='apinvoice',
            table='purchase_invoice',
        ),
    ]
