# Generated by Django 5.1.6 on 2025-03-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_apinvoice_id_remove_apinvoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apinvoice',
            table='purchasing.purchase_invoice',
        ),
    ]
