# Generated by Django 5.1.6 on 2025-03-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_apinvoice_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apinvoice',
            name='invoice_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apinvoice',
            name='purchase_id',
            field=models.CharField(max_length=20),
        ),
    ]
