# Generated by Django 5.1.6 on 2025-03-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_apinvoice_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apinvoice',
            options={'managed': False},
        ),
    ]
