# Generated by Django 5.1.6 on 2025-03-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_apinvoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apinvoice',
            options={'managed': True},
        ),
    ]
