# Generated by Django 5.1.6 on 2025-03-31 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_apinvoice_options'),
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apinvoice',
            name='purchase_id',
        ),
       
        migrations.AlterField(
            model_name='apinvoice',
            name='invoice_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
