# Generated by Django 5.1.6 on 2025-04-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_remove_apinvoice_purchase_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apinvoice',
            table='purchase_invoice',
        ),
    ]
