# Generated by Django 5.1.6 on 2025-04-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_apinvoice_table'),
    ]

    operations = [
        
    
        migrations.AlterModelTable(
            name='apinvoice',
            table='purchasing.purchase_invoice',
        ),
    ]
