# Generated by Django 5.1.6 on 2025-04-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_rename_purchase_order_apinvoice_purchase_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apinvoice',
            old_name='purchase_id',
            new_name='purchase_order',
        ),
        migrations.AlterModelTable(
            name='apinvoice',
            table='purchase_invoice',
        ),
    ]
