# Generated by Django 5.1.6 on 2025-04-12 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_rename_purchase_id_apinvoice_purchase_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentItems',
            fields=[
                ('content_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'document_items',
                'managed': False,
            },
        ),

        migrations.AddField(
            model_name='apinvoice',
            name='content_id',
            field=models.ForeignKey(blank=True, db_column='content_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.documentitems'),
        ),
    ]
