# Generated by Django 5.1.6 on 2025-04-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_documentitems_remove_apinvoice_purchase_order_and_more'),
    ]


