# Generated by Django 5.1.6 on 2025-04-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_remove_apinvoice_purchase_order'),
    ]

    