# Generated by Django 5.2 on 2025-04-16 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_remove_apinvoice_purchase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalModule',
            fields=[
                ('content_id', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invoices.documentitems')),
                ('purchase_id', models.CharField(max_length=30)),
                ('request_id', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'operations"."external_module',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='documentitems',
            table='operations"."document_items',
        ),
    ]
