# Generated by Django 5.1.6 on 2025-03-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_reference', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('tax_exempt', models.BooleanField(default=False)),
                ('vendor_website', models.URLField(blank=True, null=True)),
                ('organization_type', models.CharField(max_length=100)),
                ('separate_checks', models.BooleanField(default=False)),
                ('purchasing_cards', models.BooleanField(default=False)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('routing_no', models.CharField(blank=True, max_length=50, null=True)),
                ('requestor', models.CharField(max_length=255)),
                ('date_requested', models.DateField()),
            ],
        ),
    ]
