# Generated by Django 5.1.6 on 2025-04-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorapplication',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='vendorapplication',
            table='vendor_application',
        ),
    ]
