# Generated by Django 5.1.6 on 2025-04-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0002_alter_vendorapplication_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorapplication',
            old_name='purchasing_cards',
            new_name='purchasing_card',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='id',
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='account_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='application_reference',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='fax',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='organization_type',
            field=models.CharField(choices=[('Corporation', 'Corporation'), ('LLC', 'LLC'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Partnership', 'Partnership'), ('Nonprofit', 'Nonprofit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='routing_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True),
        ),
    ]
