# Generated by Django 5.1.6 on 2025-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseQuotation',
            fields=[
                ('quotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(max_length=50)),
                ('document_no', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('valid_date', models.DateField()),
                ('document_date', models.DateField()),
                ('required_date', models.DateField()),
                ('total_before_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('freight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
