# Generated by Django 5.1.6 on 2025-04-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasequotation',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='purchasequotation',
            table='purchase_quotation',
        ),
    ]
