# Generated by Django 5.1.6 on 2025-04-02 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_quotation', '0002_alter_purchasequotation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationContents',
            fields=[
                ('quotation_content_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"purchasing"."quotation_contents"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"admin"."vendor"',
            },
        ),
        migrations.AlterModelOptions(
            name='purchasequotation',
            options={},
        ),
        migrations.RemoveField(
            model_name='purchasequotation',
            name='vendor_code',
        ),
        migrations.AlterField(
            model_name='purchasequotation',
            name='quotation_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='purchasequotation',
            table='"purchasing"."purchase_quotation"',
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='quotation_contents',
            field=models.ForeignKey(db_column='quotation_content_id', default=' ', on_delete=django.db.models.deletion.CASCADE, to='purchase_quotation.quotationcontents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='vendor',
            field=models.ForeignKey(db_column='vendor_code', default=' ', on_delete=django.db.models.deletion.CASCADE, to='purchase_quotation.vendor'),
            preserve_default=False,
        ),
    ]
