# Generated by Django 5.1.6 on 2025-04-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_quotation', '0003_quotationcontents_vendor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationcontents',
            options={'managed': True},
        ),
    ]
