# Generated by Django 5.1.6 on 2025-04-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_quotation', '0004_alter_quotationcontents_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationcontents',
            name='quotation_content_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
