# Generated by Django 5.1.6 on 2025-04-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_quotation', '0005_alter_quotationcontents_quotation_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasequotation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
