# Generated by Django 5.1.6 on 2025-04-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_quotation', '0006_alter_purchasequotation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasequotation',
            name='quotation_contents',
        ),
        migrations.AlterField(
            model_name='quotationcontents',
            name='quotation_content_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
