# Generated by Django 5.1.6 on 2025-04-08 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRF', '0008_remove_purchaserequest_quotation_content_id_and_more'),
        ('purchase_quotation', '0007_remove_purchasequotation_quotation_contents_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuotationContents',
        ),
        migrations.RenameField(
            model_name='purchasequotation',
            old_name='vendor',
            new_name='vendor_code',
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='delivery_loc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='downpayment_request',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='request_id',
            field=models.ForeignKey(db_column='request_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_quotations', to='PRF.purchaserequest'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchasequotation',
            name='document_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
