# Generated by Django 5.1.6 on 2025-04-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_quotation', '0008_delete_quotationcontents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasequotation',
            name='document_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
