# Generated by Django 5.1.6 on 2025-03-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="min_stock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
