# Generated by Django 5.1.6 on 2025-03-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
            
                ('request_type', models.CharField(default='PROJECT', max_length=50)),
                ('date_requested', models.DateField()),
                ('date_valid', models.DateField()),
                ('document_date', models.DateField()),
            ],
        ),
    ]
