# Generated by Django 5.1.6 on 2025-04-02 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationContents',
            fields=[
                ('request_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'quotation_contents',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='department',
            new_name='purchase_item',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='date_requested',
            new_name='required_date',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='date_valid',
            new_name='valid_date',
        ),
       
        migrations.RemoveField(
            model_name='purchaserequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='request_type',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approval_id',
            field=models.CharField(default='DEFAULT_APPROVAL', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='employee_id',
            field=models.CharField(default='EMP0001', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='material_id',
            field=models.CharField(default='MAT0001', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='purchase_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='purchase_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='request_id',
            field=models.OneToOneField(db_column='request_id', default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PRF.quotationcontents'),
        ),
    ]
