# Generated by Django 5.1.6 on 2025-04-02 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRF', '0002_quotationcontents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_id',
            field=models.OneToOneField(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PRF.quotationcontents'),
        ),
    ]
