# Generated by Django 5.1.6 on 2025-04-02 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRF', '0003_alter_purchaserequest_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('approval_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"management"."management_approvals"',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"admin"."assets"',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"human_resources"."employees"',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"admin"."raw_materials"',
            },
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='purchase_item',
        ),
        migrations.AlterModelTable(
            name='purchaserequest',
            table='purchase_requests',
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='approval_id',
            field=models.ForeignKey(blank=True, db_column='approval_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='PRF.approval'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='asset_id',
            field=models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='PRF.asset'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='employee_id',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='PRF.employee'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='material_id',
            field=models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='PRF.material'),
        ),
        migrations.DeleteModel(
            name='QuotationContents',
        ),
    ]
