# Generated by Django 5.1.6 on 2025-04-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRF', '0004_approval_asset_employee_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='email_address',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
