# Generated by Django 5.1.6 on 2025-04-06 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRF', '0005_purchaserequest_department_and_more'),
        ('quotation_contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='material_id',
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='department',
        ),
        
        migrations.RemoveField(
            model_name='purchaserequest',
            name='purchase_description',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='purchase_quantity',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='quotation_content_id',
            field=models.ForeignKey(blank=True, db_column='quotation_content_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='quotation_contents.quotationcontent', verbose_name='Quotation Content'),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
