# Generated by Django 5.1.6 on 2025-04-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRF', '0006_remove_purchaserequest_asset_id_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='employee',
            name='dept_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='quotation_id',
            field=models.CharField(blank=True, db_column='quotation_id', max_length=50, null=True, verbose_name='Quotation ID'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='req_type',
            field=models.CharField(choices=[('MATERIAL', 'Material'), ('ASSETS', 'Assets')], default='MATERIAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='approval_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='purchaserequest',
            table='"purchasing"."purchase_requests"',
        ),
    ]
