# Generated by Django 5.1.6 on 2025-04-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRF', '0008_remove_purchaserequest_quotation_content_id_and_more'),
    ]

  
