# Generated by Django 5.1.6 on 2025-04-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRF', '0009_remove_purchaserequest_quotation_content_id_and_more'),
    ]

   
    
