# Generated by Django 5.1.6 on 2025-04-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRF', '0010_remove_employee_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='quotation_content_id',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='quotation_id',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='req_type',
        ),
    ]
