# Generated by Django 5.1.6 on 2025-04-02 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInspection',
            fields=[
                ('inspection_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'batch_inspection',
            },
        ),
        migrations.CreateModel(
            name='CreditMemo',
            fields=[
                ('credit_memo_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('document_no', models.IntegerField()),
                ('document_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dpm_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dpm_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inspection', models.ForeignKey(db_column='inspection_id', on_delete=django.db.models.deletion.CASCADE, to='credit_memo.batchinspection')),
            ],
            options={
                'db_table': 'credit_memo',
            },
        ),
    ]
