# Generated by Django 5.2 on 2025-04-16 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_inspection', '0001_initial'),
        ('credit_memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditmemo',
            name='inspection',
            field=models.ForeignKey(db_column='inspection_id', on_delete=django.db.models.deletion.CASCADE, to='batch_inspection.inspection'),
        ),
        migrations.DeleteModel(
            name='BatchInspection',
        ),
    ]
