# Generated by Django 5.2 on 2025-04-16 07:51

import django.db.models.deletion
import received_shipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_order', '0005_shipment_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.CharField(default=received_shipments.models.Shipment.generate_shipment_id, max_length=100, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('purchase_id', models.ForeignKey(db_column='purchase_id', on_delete=django.db.models.deletion.CASCADE, to='purchase_order.purchaseorder')),
            ],
            options={
                'db_table': 'received_shipments',
            },
        ),
    ]
