# Generated by Django 5.1.6 on 2025-04-06 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"admin"."assets"',
            },
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('material_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"admin"."raw_materials"',
            },
        ),
        migrations.CreateModel(
            name='QuotationContent',
            fields=[
                ('quotation_content_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_code', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_quantity', models.IntegerField()),
                ('asset_id', models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_contents', to='quotation_contents.assets')),
                ('material_id', models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_contents', to='quotation_contents.rawmaterials')),
            ],
            options={
                'db_table': 'quotation_contents',
                'managed': True,
            },
        ),
    ]
