# Generated by Django 5.1.6 on 2025-04-06 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRF', '0007_remove_purchaserequest_quotation_content_id_and_more'),
        ('quotation_contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationcontent',
            name='request_id',
            field=models.ForeignKey(db_column='request_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_contents', to='PRF.purchaserequest'),
        ),
        migrations.AlterField(
            model_name='quotationcontent',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='quotationcontent',
            name='quotation_content_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quotationcontent',
            name='tax_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotationcontent',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotationcontent',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
