# Generated by Django 5.1.6 on 2025-04-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation_contents', '0002_quotationcontent_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
